language: php
php:
  - "5.4"
before_script:
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "short_open_tag = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "[production]" > tests/config.local.ini
  - echo "server.domain = localhost:8080" >> tests/config.local.ini
  - echo 'server.baseUrl = ""' >> tests/config.local.ini
  - chmod a+w cache/*
  - composer self-update
  - composer install
services:
  - memcached
script: "./vendor/bin/phpunit"
notificaitons:
  irc: "irc.freenode.org#kwf"
